// SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Impstation.Thaven;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Impstation.Thaven.Eui;

[GenerateTypedNameReferences]
public sealed partial class MoodContainer : BoxContainer
{
    public MoodContainer(ThavenMood? mood = null, bool isShared = false)
    {
        RobustXamlLoader.Load(this);
        GlobalMoodLabel.Visible = isShared;

        if (mood != null)
        {
            ThavenMoodTitle.Text = mood.GetLocName();
            ThavenMoodContent.TextRope = new Rope.Leaf(mood.GetLocDesc());
        }
    }
}

