// SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
// SPDX-FileCopyrightText: 2026 PureBreadBagel
// SPDX-License-Identifier: AGPL-3.0-or-later

using System;
using Content.Shared._Jamboree.DnaCloner;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client._Jamboree.DnaCloner.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CentralCommandDnaClonerWindow : DefaultWindow
    {

        public event Action<NetEntity>? OnRespawnRequested;// JAMBOREE - Basically ran when the name is clicked in GUI.

        public CentralCommandDnaClonerWindow() // calls the CentralCommandDnaClonerWindow.
        {
            IoCManager.InjectDependencies(this); // Just loads the libraries for the GUI i guess. The one with the [Dependancy] tags
            RobustXamlLoader.Load(this); // loads the .xaml file (centralcommanddnaclonerwindow.xaml)
        }

        public void Populate(CentralCommandDnaClonerConsoleBoundUserInterfaceState state)
        {
            NameList.RemoveAllChildren(); // RESET the list so it doesnt add onto names. No dupes allowed!
            StatusLabel.Text = Loc.GetString($"centralcommand-dnacloner-status-{state.Status}"); // Just shows a label on the DNA cloning status. If its ready or not.
            BiomassLabel.Text = Loc.GetString("centralcommand-dnacloner-biomass", // shows how much biomass machine has.
                ("available", state.Biomass),
                ("required", state.BiomassCost));

            if (state.MindNames.Count == 0) // if theres no people RR'd, display no records with hailing nt lol.
            {
                var empty = new Label
                {
                    Text = Loc.GetString("centralcommand-dnacloner-no-records"),
                    HorizontalAlignment = HAlignment.Center,
                };
                NameList.AddChild(empty);
                return;
            }

            foreach (var row in state.MindNames) // For each name in the Minds without a body or rotted...
            {
                var button = new Button // create a new button for them.
                {
                    Text = row.BodyState switch // switch here means it produces a value.
                    {
                        CentralCommandDnaClonerBodyState.Lost => // if the body got round removed
                            Loc.GetString("centralcommand-dnacloner-entry-body-lost", ("name", row.Name)), // show the minds name, and button.
                        CentralCommandDnaClonerBodyState.Rotted =>
                            Loc.GetString("centralcommand-dnacloner-entry-body-rotted", ("name", row.Name)), // show the minds name with "(Rotted)" and button.
                        _ => row.Name,
                    },
                    HorizontalExpand = true,

                };

                var mind = row.Id; // entity ids into local, because lambada nonsense or whatever.
                button.OnPressed += _ => OnRespawnRequested?.Invoke(mind); // New event that makes the event raise for body cloning.
                NameList.AddChild(button); // JUST ADD THE BUTTONS WITH THE NAMES GOD DAMN IT.
            }
        }
    }
}
